[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#E50000"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FFFFFF"

[browser]
gatherUsageStats = false